# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.runs/synth_1/pcileech_squirrel_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.cache/wt [current_project]
set_property parent.project_path D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_bar_zero4k.coe
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace.coe
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace_writemask.coe
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/pcileech_cfgspace_writemask.coe
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/pcileech_bar_zero4k.coe
add_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/pcileech_cfgspace.coe
read_verilog D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_header.svh
set_property file_type "Verilog Header" [get_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_header.svh]
read_verilog -library xil_defaultlib -sv {
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_com.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_fifo.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_ft601.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_mux.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_a7.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_cfg_a7.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_tlp_a7.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_bar_controller.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_cfgspace_shadow.sv
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_squirrel_top.sv
}
read_verilog -library xil_defaultlib {
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_null_gen.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_pipeline.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_top.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_pipeline.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_thrtl_ctl.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_core_top.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_common.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_rx_valid_filter_7x.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_top.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_wrapper.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_cpllpd_ovrd.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_drp.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_rate.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_reset.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtx_cpllpd_ovrd.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie2_top.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_7x.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_7x.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_top_7x.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_brams_7x.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_lane.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_misc.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_pipeline.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_top.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_clock.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_drp.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_eq.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_rate.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_reset.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_sync.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_user.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_wrapper.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_drp.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_reset.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_wrapper.v
  D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_rxeq_scan.v
}
read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/bram_pcie_cfgspace.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/bram_pcie_cfgspace/bram_pcie_cfgspace_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64/fifo_64_64.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64/fifo_64_64.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64/fifo_64_64_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64/fifo_64_64_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_34_34/fifo_34_34_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2_ooc.xdc]

read_ip -quiet D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2.xci
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/constrs_1/imports/src/pcileech_squirrel.xdc
set_property used_in_implementation false [get_files D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/constrs_1/imports/src/pcileech_squirrel.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/utils_1/imports/synth_1/pcileech_squirrel_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top pcileech_squirrel_top -part xc7a35tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pcileech_squirrel_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file pcileech_squirrel_top_utilization_synth.rpt -pb pcileech_squirrel_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
