#*****************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# pcileech_squirrel.tcl: Tcl script for re-creating project 'pcileech_squirrel'
#
# Generated by Vivado on Sun Dec 08 23:29:00 +0800 2024
# IP Build 5239520 on Sun Nov 10 16:12:51 MST 2024
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (pcileech_squirrel.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_null_gen.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_pipeline.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_top.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_pipeline.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_thrtl_ctl.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_core_top.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_common.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_rx_valid_filter_7x.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_top.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_wrapper.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_cpllpd_ovrd.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_drp.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_rate.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_reset.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtx_cpllpd_ovrd.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie2_top.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_7x.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_7x.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_top_7x.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_brams_7x.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_lane.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_misc.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_pipeline.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_top.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_clock.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_drp.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_eq.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_rate.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_reset.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_sync.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_user.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_wrapper.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_drp.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_reset.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_wrapper.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_rxeq_scan.v"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_header.svh"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_com.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_fifo.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_ft601.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_mux.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_a7.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_cfg_a7.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_tlp_a7.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_bar_controller.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_cfgspace_shadow.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_squirrel_top.sv"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_bar_zero4k.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace_writemask.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/pcileech_cfgspace_writemask.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/bram_bar_zero4k.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/pcileech_bar_zero4k.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/pcileech_cfgspace.coe"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64/fifo_64_64.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/bram_pcie_cfgspace.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xci"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/constrs_1/imports/src/pcileech_squirrel.xdc"
#    "D:/code/pcileech-wifi-main/pcileech_squirrel/pcileech_squirrel.srcs/utils_1/imports/synth_1/pcileech_squirrel_top.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_null_gen.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_pipeline.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_top.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_pipeline.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_thrtl_ctl.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_core_top.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_common.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_rx_valid_filter_7x.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_top.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_wrapper.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_cpllpd_ovrd.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_drp.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_rate.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_reset.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtx_cpllpd_ovrd.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie2_top.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_7x.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_7x.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_top_7x.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_brams_7x.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_lane.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_misc.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_pipeline.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_top.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_clock.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_drp.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_eq.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_rate.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_reset.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_sync.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_user.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_wrapper.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_drp.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_reset.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_wrapper.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_rxeq_scan.v"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_header.svh"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_com.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_fifo.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_ft601.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_mux.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_a7.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_cfg_a7.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_tlp_a7.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_bar_controller.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_cfgspace_shadow.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_squirrel_top.sv"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_bar_zero4k.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace_writemask.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/pcileech_cfgspace_writemask.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/bram_bar_zero4k.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/pcileech_bar_zero4k.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/pcileech_cfgspace.coe"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64/fifo_64_64.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/bram_pcie_cfgspace.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xci"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/constrs_1/imports/src/pcileech_squirrel.xdc"]"\
 "[file normalize "$origin_dir/pcileech_squirrel/pcileech_squirrel.srcs/utils_1/imports/synth_1/pcileech_squirrel_top.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "pcileech_squirrel"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "pcileech_squirrel.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/pcileech_squirrel"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7a35tfgg484-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7a35tfgg484-2" -objects $obj
set_property -name "platform.description" -value "Vivado generated DSA" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "5" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "5" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "5" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "5" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "5" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "5" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "5" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_null_gen.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_rx_pipeline.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_top.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_pipeline.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_axi_basic_tx_thrtl_ctl.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_core_top.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_common.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_rx_valid_filter_7x.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_top.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gt_wrapper.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_cpllpd_ovrd.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_drp.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_rate.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtp_pipe_reset.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_gtx_cpllpd_ovrd.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie2_top.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_7x.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_7x.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_bram_top_7x.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_brams_7x.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_lane.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_misc.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_pipe_pipeline.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pcie_top.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_clock.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_drp.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_eq.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_rate.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_reset.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_sync.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_user.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_pipe_wrapper.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_drp.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_reset.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_qpll_wrapper.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/pcie_7x/pcie_7x_0_rxeq_scan.v"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_header.svh"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_com.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_fifo.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_ft601.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_mux.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_a7.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_cfg_a7.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_pcie_tlp_a7.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_bar_controller.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_tlps128_cfgspace_shadow.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/pcileech-wifi-main/src/pcileech_squirrel_top.sv"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_bar_zero4k.coe"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace.coe"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/imports/ip/pcileech_cfgspace_writemask.coe"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/pcileech_cfgspace_writemask.coe" ]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/bram_bar_zero4k.xci"]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_bar_zero4k/pcileech_bar_zero4k.coe" ]\
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/pcileech_cfgspace.coe" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "src/pcileech_header.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "src/pcileech_com.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_fifo.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_ft601.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_mux.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_pcie_a7.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_pcie_cfg_a7.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_pcie_tlp_a7.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_tlps128_bar_controller.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_tlps128_cfgspace_shadow.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "src/pcileech_squirrel_top.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "bram_bar_zero4k/bram_bar_zero4k.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "pcileech_squirrel_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_134_134_clk1_bar_rdrsp/fifo_134_134_clk1_bar_rdrsp.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_134_134_clk2_rxfifo/fifo_134_134_clk2_rxfifo.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_32_32_clk1_comtx/fifo_32_32_clk1_comtx.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_134_134_clk2/fifo_134_134_clk2.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_134_134_clk2/fifo_134_134_clk2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_64_64_clk1_fifocmd/fifo_64_64_clk1_fifocmd.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_256_32_clk2_comtx/fifo_256_32_clk2_comtx.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64/fifo_64_64.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_64_64/fifo_64_64.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_32_32_clk2/fifo_32_32_clk2.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_32_32_clk2/fifo_32_32_clk2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_129_129_clk1/fifo_129_129_clk1.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_129_129_clk1/fifo_129_129_clk1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_49_49_clk2/fifo_49_49_clk2.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_49_49_clk2/fifo_49_49_clk2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_1_1_clk2/fifo_1_1_clk2.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_1_1_clk2/fifo_1_1_clk2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/bram_pcie_cfgspace/bram_pcie_cfgspace.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "bram_pcie_cfgspace/bram_pcie_cfgspace.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_74_74_clk1_bar_rd1/fifo_74_74_clk1_bar_rd1.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "drom_pcie_cfgspace_writemask/drom_pcie_cfgspace_writemask.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_34_34/fifo_34_34.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_43_43_clk2/fifo_43_43_clk2.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_43_43_clk2/fifo_43_43_clk2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xci"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_64_64_clk2_comrx/fifo_64_64_clk2_comrx.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/constrs_1/imports/src/pcileech_squirrel.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "src/pcileech_squirrel.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7a35tfgg484-2" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "pcileech_squirrel_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/pcileech_squirrel/pcileech_squirrel.srcs/utils_1/imports/synth_1/pcileech_squirrel_top.dcp" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset utils_1 $f]
}

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/pcileech_squirrel_top.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7a35tfgg484-2 -flow {Vivado Synthesis 2022} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2022" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7a35tfgg484-2" -objects $obj
set_property -name "incremental_checkpoint" -value "$proj_dir/${_xil_proj_name_}.srcs/utils_1/imports/synth_1/pcileech_squirrel_top.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7a35tfgg484-2 -flow {Vivado Implementation 2022} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2022" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7a35tfgg484-2" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.bin_file" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
