# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci
# IP: The module: 'fifo_141_141_clk1_bar_wr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xci
# IP: The module: 'fifo_141_141_clk1_bar_wr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/code/pcileech-wifi/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/fifo_141_141_clk1_bar_wr/fifo_141_141_clk1_bar_wr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_141_141_clk1_bar_wr'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
